# Generated by Django 6.0.2 on 2026-03-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
