# Generated by Django 6.0.2 on 2026-03-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_sensordata_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='value',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='turbidity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
